#:schema https://jj-vcs.github.io/jj/latest/config-schema.json
[ui]
editor = "nvim"
merge-editor = ":builtin"


[user]
name = "Philipp Renz"
email = "philipp@reactwise.com" 

[aliases]
spr = ["util", "exec", "--", "jj-spr"]
